name: Build and Push to Folder Overview

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout folder-notes
        uses: actions/checkout@v3
        with:
          repository: LostPaul/obsidian-folder-notes
          fetch-depth: 0
          submodules: recursive
          path: folder-notes

      - name: Install dependencies
        run: |
          cd folder-notes
          npm install

      - name: Build folder-overview
        run: |
          cd folder-notes
          npm run fv-build  # This will run esbuild.config.mjs

      - name: Verify build output
        run: |
          ls -la folder-notes/src/obsidian-folder-overview/
          ls -la folder-notes/dist/

      - name: Checkout folder-overview
        uses: actions/checkout@v3
        with:
          repository: LostPaul/obsidian-folder-overview
          token: ${{ secrets.PAT }}
          ref: main
          path: folder-overview

      - name: Copy built files to folder-overview
        run: |
          cp folder-notes/src/obsidian-folder-overview/main.js \
             folder-notes/src/obsidian-folder-overview/styles.css folder-overview/

      - name: Commit and push built files
        run: |
          cd folder-overview
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add main.js styles.css
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add built files for release"
            git push origin main
          fi
