name: Build and Push to Folder Overview

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to build"
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout folder-notes
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use tag from input if triggered manually
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "GITHUB_REF=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi

      - name: Run fv-build
        run: |
          npm install
          npm run fv-build

      - name: Checkout folder-overview
        uses: actions/checkout@v3
        with:
          repository: LostPaul/obsidian-folder-overview
          token: ${{ secrets.PAT }}
          path: folder-overview

      - name: Copy built files to folder-overview
        run: |
          cp main.js styles.css folder-overview/

      - name: Create branch and push to folder-overview
        run: |
          cd folder-overview
          git checkout -b auto-build-${{ github.ref_name }}
          git add main.js styles.css
          git commit -m "Auto-build from folder-notes ${{ github.ref_name }}"
          git push origin auto-build-${{ github.ref_name }}

      - name: Trigger release workflow in folder-overview
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/LostPaul/obsidian-folder-overview/actions/workflows/release.yml/dispatches \
          -d '{"ref": "main", "inputs": {"tag": "${{ github.ref_name }}", "branch": "auto-build-${{ github.ref_name }}"}}'
