name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - uses: actions/cache@v4  
        with:
          path: .cache
          key: mkdocs-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            mkdocs-${{ runner.os }}-
      
      - run: pip install mkdocs-material mkdocs-video pillow cairosvg
      
      - working-directory: ./docs
        run: mkdocs gh-deploy --force

